### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by glycerine** [NYU-NEWS/janus#3]
Please consider adding an MIT or BSD license file at the top level.

**Comment by shuaimu** [comment]
Thank you for the catch! Added.

**Comment by glycerine** [comment]
Thank you. The GPL is not particularly commercial friendly. Would you consider using an MIT or BSD license instead?

**Comment by shuaimu** [comment]
I am protecting them from getting hurt. :)

**Comment by shuaimu** [comment]
Thanks for the suggestion! The code is not production ready so I do not want it to be commercial friendly.

**Comment by glycerine** [comment]
That's too bad. I guess I'll be using TAPIR instead of Janus then. Yours looked faster under contention, but TAPIR is MIT licensed.

**Comment by shuaimu** [comment]
That's fine. Just curious what you're using it for?
